CREATE TABLE IF NOT EXISTS placements (
  id SERIAL PRIMARY KEY,
  placement_name VARCHAR(500),
  slug VARCHAR(500),
  description TEXT,
  body_area VARCHAR(500),
  pain_level INTEGER,
  visibility_level INTEGER,
  popularity_rank INTEGER,
  is_common BOOLEAN,
  source VARCHAR(500),
  timestamp VARCHAR(500),
  urls TEXT
);

TRUNCATE TABLE placements;

INSERT INTO placements (placement_name, slug, description, body_area, pain_level, visibility_level, popularity_rank, is_common, source, timestamp, urls) VALUES ('Solar Plexus (Upper Stomach)', 'solar-plexus', 'Upper stomach area, often considered spiritually significant', 'Torso', 8, 6, 25, TRUE, NULL, NULL, NULL);
INSERT INTO placements (placement_name, slug, description, body_area, pain_level, visibility_level, popularity_rank, is_common, source, timestamp, urls) VALUES ('Calf / Shin', 'calf-shin', 'Lower leg area, popular for various tattoo styles', 'Legs', 4, 7, 12, TRUE, NULL, NULL, NULL);
INSERT INTO placements (placement_name, slug, description, body_area, pain_level, visibility_level, popularity_rank, is_common, source, timestamp, urls) VALUES ('Under Skin Implants (Subdermal)', 'subdermal-implants', '3D implants placed under the skin surface', 'Special', 9, 8, 45, FALSE, NULL, NULL, NULL);
INSERT INTO placements (placement_name, slug, description, body_area, pain_level, visibility_level, popularity_rank, is_common, source, timestamp, urls) VALUES ('Legs (journey, foundation)', 'legs', 'Entire leg area, symbolic of life journey', 'Legs', 5, 8, 15, TRUE, NULL, NULL, NULL);
INSERT INTO placements (placement_name, slug, description, body_area, pain_level, visibility_level, popularity_rank, is_common, source, timestamp, urls) VALUES ('Elbow Pit (Ditch)', 'elbow-pit', 'Inner elbow area, sensitive with thin skin', 'Arms', 9, 4, 32, TRUE, NULL, NULL, NULL);
INSERT INTO placements (placement_name, slug, description, body_area, pain_level, visibility_level, popularity_rank, is_common, source, timestamp, urls) VALUES ('Behind Knee Crease', 'behind-knee', 'Back of knee area, sensitive and often hidden', 'Legs', 8, 4, 38, TRUE, NULL, NULL, NULL);
INSERT INTO placements (placement_name, slug, description, body_area, pain_level, visibility_level, popularity_rank, is_common, source, timestamp, urls) VALUES ('Spine (spiritual)', 'spine', 'Vertical back area, spiritually significant', 'Back', 7, 5, 18, TRUE, NULL, NULL, NULL);
INSERT INTO placements (placement_name, slug, description, body_area, pain_level, visibility_level, popularity_rank, is_common, source, timestamp, urls) VALUES ('Web of Hand', 'hand-web', 'Skin between thumb and index finger', 'Hands', 9, 9, 28, TRUE, NULL, NULL, NULL);
INSERT INTO placements (placement_name, slug, description, body_area, pain_level, visibility_level, popularity_rank, is_common, source, timestamp, urls) VALUES ('Sole of Foot', 'sole-foot', 'Bottom of foot, extremely sensitive', 'Feet', 10, 3, 48, FALSE, NULL, NULL, NULL);
INSERT INTO placements (placement_name, slug, description, body_area, pain_level, visibility_level, popularity_rank, is_common, source, timestamp, urls) VALUES ('Back (strength, large canvas)', 'back', 'Large back area for extensive artwork', 'Back', 6, 6, 8, TRUE, NULL, NULL, NULL);
INSERT INTO placements (placement_name, slug, description, body_area, pain_level, visibility_level, popularity_rank, is_common, source, timestamp, urls) VALUES ('Feet (connection to earth)', 'feet', 'Foot area, symbolic of grounding', 'Feet', 8, 7, 22, TRUE, NULL, NULL, NULL);
INSERT INTO placements (placement_name, slug, description, body_area, pain_level, visibility_level, popularity_rank, is_common, source, timestamp, urls) VALUES ('Face', 'face', 'Facial area, highly visible and culturally significant', 'Face', 9, 10, 42, FALSE, NULL, NULL, NULL);
INSERT INTO placements (placement_name, slug, description, body_area, pain_level, visibility_level, popularity_rank, is_common, source, timestamp, urls) VALUES ('Forearm', 'forearm', 'Lower arm area, highly visible', 'Arms', 5, 9, 5, TRUE, NULL, NULL, NULL);
INSERT INTO placements (placement_name, slug, description, body_area, pain_level, visibility_level, popularity_rank, is_common, source, timestamp, urls) VALUES ('Thigh (large canvas)', 'thigh', 'Upper leg area, large surface for artwork', 'Legs', 6, 5, 10, TRUE, NULL, NULL, NULL);
INSERT INTO placements (placement_name, slug, description, body_area, pain_level, visibility_level, popularity_rank, is_common, source, timestamp, urls) VALUES ('Buttocks', 'buttocks', 'Buttock area, often hidden', 'Torso', 5, 3, 30, TRUE, NULL, NULL, NULL);
INSERT INTO placements (placement_name, slug, description, body_area, pain_level, visibility_level, popularity_rank, is_common, source, timestamp, urls) VALUES ('Back', 'back-general', 'General back area', 'Back', 6, 5, 9, TRUE, NULL, NULL, NULL);
INSERT INTO placements (placement_name, slug, description, body_area, pain_level, visibility_level, popularity_rank, is_common, source, timestamp, urls) VALUES ('Lower Back', 'lower-back', 'Lower back area, popular placement', 'Back', 5, 4, 13, TRUE, NULL, NULL, NULL);
INSERT INTO placements (placement_name, slug, description, body_area, pain_level, visibility_level, popularity_rank, is_common, source, timestamp, urls) VALUES ('Hands (Polynesian, criminal, spiritual)', 'hands', 'Entire hand area, culturally significant', 'Hands', 8, 10, 20, TRUE, NULL, NULL, NULL);
INSERT INTO placements (placement_name, slug, description, body_area, pain_level, visibility_level, popularity_rank, is_common, source, timestamp, urls) VALUES ('Arms (genealogy, achievements)', 'arms', 'Entire arm area, symbolic of accomplishments', 'Arms', 6, 8, 7, TRUE, NULL, NULL, NULL);
INSERT INTO placements (placement_name, slug, description, body_area, pain_level, visibility_level, popularity_rank, is_common, source, timestamp, urls) VALUES ('Hand', 'hand', 'Hand surface, highly visible', 'Hands', 8, 10, 17, TRUE, NULL, NULL, NULL);
INSERT INTO placements (placement_name, slug, description, body_area, pain_level, visibility_level, popularity_rank, is_common, source, timestamp, urls) VALUES ('Finger (micro tattoos)', 'finger', 'Finger area for small tattoos', 'Hands', 7, 9, 23, TRUE, NULL, NULL, NULL);
INSERT INTO placements (placement_name, slug, description, body_area, pain_level, visibility_level, popularity_rank, is_common, source, timestamp, urls) VALUES ('Neck (protection, status)', 'neck', 'Neck area, symbolic and highly visible', 'Neck', 8, 10, 16, TRUE, NULL, NULL, NULL);
INSERT INTO placements (placement_name, slug, description, body_area, pain_level, visibility_level, popularity_rank, is_common, source, timestamp, urls) VALUES ('Front Thigh', 'front-thigh', 'Front upper leg area', 'Legs', 6, 6, 19, TRUE, NULL, NULL, NULL);
INSERT INTO placements (placement_name, slug, description, body_area, pain_level, visibility_level, popularity_rank, is_common, source, timestamp, urls) VALUES ('Chest', 'chest', 'Chest area, often for meaningful pieces', 'Torso', 7, 7, 6, TRUE, NULL, NULL, NULL);
INSERT INTO placements (placement_name, slug, description, body_area, pain_level, visibility_level, popularity_rank, is_common, source, timestamp, urls) VALUES ('Palm Lines (Life/Heart/Head Lines)', 'palm-lines', 'Palm area following natural lines', 'Hands', 9, 8, 43, FALSE, NULL, NULL, NULL);
INSERT INTO placements (placement_name, slug, description, body_area, pain_level, visibility_level, popularity_rank, is_common, source, timestamp, urls) VALUES ('Under Tongue', 'under-tongue', 'Bottom of tongue, extremely hidden', 'Special', 10, 1, 50, FALSE, NULL, NULL, NULL);
INSERT INTO placements (placement_name, slug, description, body_area, pain_level, visibility_level, popularity_rank, is_common, source, timestamp, urls) VALUES ('Behind Ears (Protection)', 'behind-ears', 'Area behind ears, discreet placement', 'Head', 6, 4, 29, TRUE, NULL, NULL, NULL);
INSERT INTO placements (placement_name, slug, description, body_area, pain_level, visibility_level, popularity_rank, is_common, source, timestamp, urls) VALUES ('Ankle', 'ankle', 'Ankle area, popular for smaller tattoos', 'Legs', 6, 7, 11, TRUE, NULL, NULL, NULL);
INSERT INTO placements (placement_name, slug, description, body_area, pain_level, visibility_level, popularity_rank, is_common, source, timestamp, urls) VALUES ('Eye Corners', 'eye-corners', 'Corner of eyes, extremely sensitive', 'Face', 10, 10, 49, FALSE, NULL, NULL, NULL);
INSERT INTO placements (placement_name, slug, description, body_area, pain_level, visibility_level, popularity_rank, is_common, source, timestamp, urls) VALUES ('Scalp Under Hair', 'scalp', 'Scalp area hidden by hair', 'Head', 5, 2, 40, FALSE, NULL, NULL, NULL);
INSERT INTO placements (placement_name, slug, description, body_area, pain_level, visibility_level, popularity_rank, is_common, source, timestamp, urls) VALUES ('Upper Back', 'upper-back', 'Upper back area, larger canvas', 'Back', 6, 4, 14, TRUE, NULL, NULL, NULL);
INSERT INTO placements (placement_name, slug, description, body_area, pain_level, visibility_level, popularity_rank, is_common, source, timestamp, urls) VALUES ('Between Toes', 'between-toes', 'Skin between toes, sensitive area', 'Feet', 8, 3, 46, FALSE, NULL, NULL, NULL);
INSERT INTO placements (placement_name, slug, description, body_area, pain_level, visibility_level, popularity_rank, is_common, source, timestamp, urls) VALUES ('Inside Nostrils', 'inside-nostrils', 'Inside nose area, extremely hidden', 'Special', 10, 1, 51, FALSE, NULL, NULL, NULL);
INSERT INTO placements (placement_name, slug, description, body_area, pain_level, visibility_level, popularity_rank, is_common, source, timestamp, urls) VALUES ('Between Fingers', 'between-fingers', 'Skin between fingers', 'Hands', 8, 6, 35, TRUE, NULL, NULL, NULL);
INSERT INTO placements (placement_name, slug, description, body_area, pain_level, visibility_level, popularity_rank, is_common, source, timestamp, urls) VALUES ('Under Breast Tissue', 'under-breast', 'Area under breast, sensitive and hidden', 'Torso', 7, 2, 37, FALSE, NULL, NULL, NULL);
INSERT INTO placements (placement_name, slug, description, body_area, pain_level, visibility_level, popularity_rank, is_common, source, timestamp, urls) VALUES ('Third Eye (Forehead Center)', 'third-eye', 'Center forehead, spiritually significant', 'Face', 9, 10, 44, FALSE, NULL, NULL, NULL);
INSERT INTO placements (placement_name, slug, description, body_area, pain_level, visibility_level, popularity_rank, is_common, source, timestamp, urls) VALUES ('Ribcage (personal)', 'ribcage', 'Side torso area, sensitive but popular', 'Torso', 8, 4, 21, TRUE, NULL, NULL, NULL);
INSERT INTO placements (placement_name, slug, description, body_area, pain_level, visibility_level, popularity_rank, is_common, source, timestamp, urls) VALUES ('Shoulder / Deltoid', 'shoulder', 'Shoulder area, popular placement', 'Arms', 5, 7, 4, TRUE, NULL, NULL, NULL);
INSERT INTO placements (placement_name, slug, description, body_area, pain_level, visibility_level, popularity_rank, is_common, source, timestamp, urls) VALUES ('Thigh', 'thigh-general', 'General thigh area', 'Legs', 6, 5, 11, TRUE, NULL, NULL, NULL);
INSERT INTO placements (placement_name, slug, description, body_area, pain_level, visibility_level, popularity_rank, is_common, source, timestamp, urls) VALUES ('Back of neck (protection)', 'back-neck', 'Back neck area, symbolic placement', 'Neck', 7, 6, 24, TRUE, NULL, NULL, NULL);
INSERT INTO placements (placement_name, slug, description, body_area, pain_level, visibility_level, popularity_rank, is_common, source, timestamp, urls) VALUES ('Neck', 'neck-general', 'General neck area', 'Neck', 8, 9, 16, TRUE, NULL, NULL, NULL);
INSERT INTO placements (placement_name, slug, description, body_area, pain_level, visibility_level, popularity_rank, is_common, source, timestamp, urls) VALUES ('Behind ear (discreet)', 'behind-ear', 'Area behind ear, discreet placement', 'Head', 6, 4, 27, TRUE, NULL, NULL, NULL);
INSERT INTO placements (placement_name, slug, description, body_area, pain_level, visibility_level, popularity_rank, is_common, source, timestamp, urls) VALUES ('Chest / Sternum / Under-bust', 'chest-sternum', 'Chest and sternum area', 'Torso', 8, 5, 26, TRUE, NULL, NULL, NULL);
INSERT INTO placements (placement_name, slug, description, body_area, pain_level, visibility_level, popularity_rank, is_common, source, timestamp, urls) VALUES ('Armpit', 'armpit', 'Armpit area, extremely sensitive', 'Arms', 10, 2, 47, FALSE, NULL, NULL, NULL);
INSERT INTO placements (placement_name, slug, description, body_area, pain_level, visibility_level, popularity_rank, is_common, source, timestamp, urls) VALUES ('Sacral (Lower Stomach)', 'sacral', 'Lower stomach area, spiritually significant', 'Torso', 7, 4, 31, TRUE, NULL, NULL, NULL);
INSERT INTO placements (placement_name, slug, description, body_area, pain_level, visibility_level, popularity_rank, is_common, source, timestamp, urls) VALUES ('Heart Chakra (Chest Center)', 'heart-chakra', 'Center chest, spiritually significant', 'Torso', 7, 7, 33, TRUE, NULL, NULL, NULL);
INSERT INTO placements (placement_name, slug, description, body_area, pain_level, visibility_level, popularity_rank, is_common, source, timestamp, urls) VALUES ('Ear Canal Interior', 'ear-canal', 'Inside ear canal, extremely hidden', 'Special', 9, 1, 52, FALSE, NULL, NULL, NULL);
INSERT INTO placements (placement_name, slug, description, body_area, pain_level, visibility_level, popularity_rank, is_common, source, timestamp, urls) VALUES ('Root (Base of Spine)', 'root-spine', 'Base of spine, spiritually significant', 'Back', 7, 3, 34, TRUE, NULL, NULL, NULL);
INSERT INTO placements (placement_name, slug, description, body_area, pain_level, visibility_level, popularity_rank, is_common, source, timestamp, urls) VALUES ('Upper Arm / Bicep', 'upper-arm', 'Upper arm area, very popular placement', 'Arms', 5, 8, 3, TRUE, NULL, NULL, NULL);
INSERT INTO placements (placement_name, slug, description, body_area, pain_level, visibility_level, popularity_rank, is_common, source, timestamp, urls) VALUES ('Gums (Inside Mouth)', 'gums', 'Gum tissue inside mouth', 'Special', 10, 1, 53, FALSE, NULL, NULL, NULL);
INSERT INTO placements (placement_name, slug, description, body_area, pain_level, visibility_level, popularity_rank, is_common, source, timestamp, urls) VALUES ('Hand / Palm / Fingers / Knuckles', 'hand-palm', 'Complete hand area including palm and fingers', 'Hands', 9, 10, 19, TRUE, NULL, NULL, NULL);
INSERT INTO placements (placement_name, slug, description, body_area, pain_level, visibility_level, popularity_rank, is_common, source, timestamp, urls) VALUES ('Back Thigh', 'back-thigh', 'Back of thigh area', 'Legs', 6, 4, 20, TRUE, NULL, NULL, NULL);
INSERT INTO placements (placement_name, slug, description, body_area, pain_level, visibility_level, popularity_rank, is_common, source, timestamp, urls) VALUES ('Mid Back', 'mid-back', 'Middle back area', 'Back', 6, 4, 17, TRUE, NULL, NULL, NULL);
INSERT INTO placements (placement_name, slug, description, body_area, pain_level, visibility_level, popularity_rank, is_common, source, timestamp, urls) VALUES ('Inner lip (hidden)', 'inner-lip', 'Inside of lip, completely hidden', 'Special', 8, 1, 39, FALSE, NULL, NULL, NULL);
INSERT INTO placements (placement_name, slug, description, body_area, pain_level, visibility_level, popularity_rank, is_common, source, timestamp, urls) VALUES ('Front Neck', 'front-neck', 'Front neck area, highly visible', 'Neck', 8, 10, 36, TRUE, NULL, NULL, NULL);
INSERT INTO placements (placement_name, slug, description, body_area, pain_level, visibility_level, popularity_rank, is_common, source, timestamp, urls) VALUES ('Throat Chakra (Neck Front)', 'throat-chakra', 'Front neck, spiritually significant', 'Neck', 8, 10, 41, TRUE, NULL, NULL, NULL);
INSERT INTO placements (placement_name, slug, description, body_area, pain_level, visibility_level, popularity_rank, is_common, source, timestamp, urls) VALUES ('Foot / Toes', 'foot-toes', 'Foot and toe area', 'Feet', 8, 7, 23, TRUE, NULL, NULL, NULL);
INSERT INTO placements (placement_name, slug, description, body_area, pain_level, visibility_level, popularity_rank, is_common, source, timestamp, urls) VALUES ('Chest (bravery, heart-centered)', 'chest-heart', 'Chest area over heart', 'Torso', 7, 7, 6, TRUE, NULL, NULL, NULL);
INSERT INTO placements (placement_name, slug, description, body_area, pain_level, visibility_level, popularity_rank, is_common, source, timestamp, urls) VALUES ('Spine', 'spine-general', 'General spine area', 'Back', 7, 5, 18, TRUE, NULL, NULL, NULL);
INSERT INTO placements (placement_name, slug, description, body_area, pain_level, visibility_level, popularity_rank, is_common, source, timestamp, urls) VALUES ('Sternum (sacred)', 'sternum', 'Center chest bone area', 'Torso', 8, 6, 28, TRUE, NULL, NULL, NULL);
INSERT INTO placements (placement_name, slug, description, body_area, pain_level, visibility_level, popularity_rank, is_common, source, timestamp, urls) VALUES ('Finger Joints (Polynesian)', 'finger-joints', 'Finger joint areas', 'Hands', 8, 9, 32, TRUE, NULL, NULL, NULL);
INSERT INTO placements (placement_name, slug, description, body_area, pain_level, visibility_level, popularity_rank, is_common, source, timestamp, urls) VALUES ('Inner Thigh', 'inner-thigh', 'Inner thigh area, sensitive', 'Legs', 7, 3, 30, TRUE, NULL, NULL, NULL);
INSERT INTO placements (placement_name, slug, description, body_area, pain_level, visibility_level, popularity_rank, is_common, source, timestamp, urls) VALUES ('Stomach / Abdomen', 'stomach', 'Stomach area', 'Torso', 7, 5, 24, TRUE, NULL, NULL, NULL);
INSERT INTO placements (placement_name, slug, description, body_area, pain_level, visibility_level, popularity_rank, is_common, source, timestamp, urls) VALUES ('Collarbone Strips (Japanese Munewari)', 'collarbone', 'Collarbone area, traditional Japanese placement', 'Torso', 7, 8, 35, TRUE, NULL, NULL, NULL);
INSERT INTO placements (placement_name, slug, description, body_area, pain_level, visibility_level, popularity_rank, is_common, source, timestamp, urls) VALUES ('Upper Arm', 'upper-arm-general', 'General upper arm area', 'Arms', 5, 8, 3, TRUE, NULL, NULL, NULL);
INSERT INTO placements (placement_name, slug, description, body_area, pain_level, visibility_level, popularity_rank, is_common, source, timestamp, urls) VALUES ('Outer Forearm', 'outer-forearm', 'Outer forearm area', 'Arms', 5, 9, 9, TRUE, NULL, NULL, NULL);
INSERT INTO placements (placement_name, slug, description, body_area, pain_level, visibility_level, popularity_rank, is_common, source, timestamp, urls) VALUES ('Palate (Roof of Mouth)', 'palate', 'Roof of mouth', 'Special', 9, 1, 54, FALSE, NULL, NULL, NULL);
INSERT INTO placements (placement_name, slug, description, body_area, pain_level, visibility_level, popularity_rank, is_common, source, timestamp, urls) VALUES ('Ribs / Side', 'ribs', 'Rib cage side area', 'Torso', 8, 4, 21, TRUE, NULL, NULL, NULL);

